import { HighlightStyle } from '@codemirror/language';
import { tags } from '@lezer/highlight';

export const CODEHIGHLIGHT = HighlightStyle.define([
  { tag: tags.keyword, color: '#569cd6' },
  { tag: tags.controlKeyword, color: '#c586c0' },
  { tag: tags.operatorKeyword, color: '#569cd6' },
  { tag: tags.modifier, color: '#569cd6' },
  { tag: tags.self, color: '#569cd6' },
  { tag: tags.null, color: '#569cd6' },
  { tag: tags.atom, color: '#569cd6' },
  { tag: tags.bool, color: '#569cd6' },
  { tag: tags.string, color: '#ce9178' },
  { tag: tags.character, color: '#ce9178' },
  { tag: tags.content, color: '#ce9178' },
  { tag: tags.escape, color: '#d7ba7d' },
  { tag: tags.regexp, color: '#d16969' },
  { tag: tags.number, color: '#b5cea8' },
  { tag: tags.integer, color: '#b5cea8' },
  { tag: tags.float, color: '#b5cea8' },
  { tag: tags.comment, color: '#6a9955', fontStyle: 'italic' },
  { tag: tags.lineComment, color: '#6a9955', fontStyle: 'italic' },
  { tag: tags.blockComment, color: '#6a9955', fontStyle: 'italic' },
  { tag: tags.docComment, color: '#6a9955', fontStyle: 'italic' },
  { tag: tags.typeName, color: '#4ec9b0' },
  { tag: tags.className, color: '#4ec9b0' },
  { tag: tags.namespace, color: '#4ec9b0' },
  { tag: tags.macroName, color: '#4ec9b0' },
  { tag: tags.variableName, color: '#9cdcfe' },
  { tag: tags.propertyName, color: '#92c5f7' },
  { tag: tags.attributeName, color: '#92c5f7' },
  { tag: tags.function(tags.variableName), color: '#dcdcaa' },
  { tag: tags.function(tags.propertyName), color: '#dcdcaa' },
  { tag: tags.definition(tags.variableName), color: '#9cdcfe' },
  { tag: tags.definition(tags.propertyName), color: '#92c5f7' },
  { tag: tags.tagName, color: '#569cd6' },
  { tag: tags.attributeValue, color: '#ce9178' },
  { tag: tags.angleBracket, color: '#808080' },
  { tag: tags.operator, color: '#d4d4d4' },
  { tag: tags.punctuation, color: '#d4d4d4' },
  { tag: tags.separator, color: '#d4d4d4' },
  { tag: tags.bracket, color: '#ffd700' },
  { tag: tags.squareBracket, color: '#ffd700' },
  { tag: tags.paren, color: '#ffd700' },
  { tag: tags.brace, color: '#ffd700' },
  { tag: tags.meta, color: '#6a9955' },
  { tag: tags.annotation, color: '#6a9955' },
  { tag: tags.processingInstruction, color: '#6a9955' },
  { tag: tags.url, color: '#ce9178', textDecoration: 'underline' },
  { tag: tags.link, color: '#ce9178', textDecoration: 'underline' },
  { tag: tags.heading, color: '#569cd6', fontWeight: 'bold' },
  { tag: tags.list, color: '#d4d4d4' },
  { tag: tags.quote, color: '#6a9955', fontStyle: 'italic' },
  { tag: tags.emphasis, fontStyle: 'italic' },
  { tag: tags.strong, fontWeight: 'bold' },
  { tag: tags.strikethrough, textDecoration: 'line-through' },
  { tag: tags.monospace, fontFamily: 'Consolas, "Courier New", monospace' },
  { tag: tags.invalid, color: '#f44747', backgroundColor: '#1e3a8a' },
]);

export const AVAILABLE_LANGUAGES = [
  { label: 'TypeScript', value: 'ts' },
  { label: 'JavaScript', value: 'js' },
  { label: 'Python', value: 'py' },
  { label: 'C++', value: 'cpp' },
  { label: 'Java', value: 'java' },
  { label: 'Rust', value: 'rust' },
  { label: 'Go', value: 'go' },
  { label: 'PHP', value: 'php' },
  { label: 'SQL', value: 'sql' },
  { label: 'HTML', value: 'html' },
  { label: 'CSS', value: 'css' },
  { label: 'Markdown', value: 'md' },
  { label: 'JSON', value: 'json' },
  { label: 'XML', value: 'xml' },
  { label: 'YAML', value: 'yaml' },
  { label: 'Shell', value: 'sh' },
  { label: 'Plain Text', value: 'text' },
];
